### ISSUE TITLE
Usage with the ApiGateway module

### ISSUE THREAD

**Issue by Napas** [rmccallum81/moleculer-service-decorators#1]
Hi, is there an example how to use it with the Moleculer ApiGateway module?

**Comment by rmccallum81** [comment]
Not yet but I'll look at creating one.

**Comment by rmccallum81** [comment]
I've created an example for using the API Gateway as well as put in a fix so that mixins now work properly. Update to version 1.0.1 to get the benefits of these changes.

**Comment by Napas** [comment]
Awesome, thanks!

**Comment by Napas** [comment]
Even copy/pasted example throws: 

` ServiceSchemaError: Service name can't be empty! Maybe it is not a valid Service schema.`

Any ideas?

**Comment by rmccallum81** [comment]
What version of moleculer are you using? I was able to run it successfully using version 0.13.1 using ts-node and compiling it.
