### ISSUE TITLE
Howto Methods

### ISSUE THREAD

**Issue by heralight** [rmccallum81/moleculer-service-decorators#2]
Hi,

Thank you for your decorators...
I don't find a way to declare 'methods' in a  moleculer service, like 'authorize' with your extension, do you have perhaps a sample for this use case please ?

Thank you!

Alexandre

**Comment by rmccallum81** [comment]
Hi Alexandre

Are you referring to using a method within an action or event? In this case you just need to create the method on the class without any decorator and reference it as `this.methodName()` as usual.

If you are referring to a middleware, add them in the `service` decorator options as you would without using decorators.

I'll also look at adding these examples and perhaps a decorator for adding middleware.

Ryan

**Comment by heralight** [comment]
@rmccallum81 it's about https://moleculer.services/docs/0.12/service.html#Methods

I need this implementation to do autorisation for exemple :
https://moleculer.services/docs/0.12/moleculer-web.html#Authorization

as for services.actions, method is related to services.methods, In  ServiceOptionsToExclude you already exclude it, but not managed it after...

**Comment by ryanm-pm** [comment]
The methods in the ES6 implementation don't need any special treatment, just add them to the class. The settings section of the example is added to the service decorator input.

```
@service({settings: {...}})
class ServiceClass extends Service {
  ...
  authorize(ctx, route, req, res) {
    ...
  }
}
```

**Comment by heralight** [comment]
My bad... with typescript, 
intellij had put the function authorize in private... remove private and work as expected ! thank you very much!
