### ISSUE TITLE
Parameter validation doesn't work

### ISSUE THREAD

**Issue by pewh** [rmccallum81/moleculer-service-decorators#3]
```
@action({
        name: "getHelp",
        cache: true,
        metrics: { params: false, meta: true },
        params: {
            text: "string"
        }
    })
    public help(ctx: Context) {}
```

this command `call 'service.help' "{ "text": 123 }"` should throw ValidationError. But it doesn't.

**Comment by rmccallum81** [comment]
Thanks @pewh, I'm taking a look at this. Are you using the default `fast-validator` or are you implementing a different validator?

Also it seems you came across another issue as the action should have been called as `service.getHelp` due to the name being set on the action.

**Comment by pewh** [comment]
Hello,
I use default `fastest-validator`, and also have try to update code by removing `name`, and the unexpected behavior still happened.

**Comment by rmccallum81** [comment]
I've fixed this issue and I'll deploy it once I see if this issue #4 can go with it

**Comment by pewh** [comment]
Thanks for the fix.

I just did testing and almost case fixed expect for this:
```
	@action({
		params: {
			type: { type: 'enum', values: Object.values(TypeEnum) },
			username: { type: 'string' },
		},
	})
	public signin(ctx: ServiceBroker) {
		return true
	}
```

```
it('should reject an ValidationError when submit incorrect params', () => {
			return expect(broker.call('v1.userSession.signin')).rejects.toBeInstanceOf(Errors.ValidationError)
		})
```

when I use vanilla moleculer, the test above is passed because `type` and `username` are required.

**Comment by rmccallum81** [comment]
I've run tests with the latest code and this seems to be working as expected.
